### PR TITLE
Dont run install as root - pass password as prompt

### PR DESCRIPTION
**Pull request by colfax23**
Fix for Install issue #6

### CODE REVIEW

**Comment by remyroy** [comment]
I would also switch from using curl by default in https://github.com/ethstaker-core/stakehouse/blob/main/src/react/commands/RocketPool.ts#L11 to using wget since curl is not installed by default and wget is on Ubuntu 20.04.2 Desktop. Here is the full command from https://github.com/rocket-pool/smartnode-install for this:

```
mkdir -p ~/bin && wget https://github.com/rocket-pool/smartnode-install/releases/latest/download/rocketpool-cli-linux-amd64 -O ~/bin/rocketpool && chmod +x ~/bin/rocketpool
```

**Comment by remyroy** [comment]
Rocket Pool service installation worked but it failed the `rocketpool service start` command on a clean install of Ubuntu 20.04.2 Desktop. Here is the log:

https://gist.github.com/remyroy/cc447de6d772ec9bd64cf708b32edb94

**Comment by remyroy** [comment]
This is similar to the issue I had previously just running rocketpool on its own. User need to log out and log back in or use the `su - $USER` hack as mentioned in the discord chat log.

**Comment by colfax23** [comment]
Thanks - will address that.

**Comment by colfax23** [comment]
Alright, I believe it is all fixed now.  A few changes:
- in order to get the new permissions to be respected, I had to explicitly specify the docker group by running each command inside `sg docker`
- reworked password input to handle retires and it functions better overall
- as a result, I was able to simplify the 'installing' page
- on the status page, I moved the client name to the status grid so it is easier to see

This still encompasses:
- No longer installing or running rocketpool as root
- proper user group permission handling, across sessions, no logout/login needed ever

**Comment by remyroy** [comment]
It works fine on my side on a clean install of Ubuntu 20.04.2 Desktop. Rocket pool was installed and the service was installed sucessfully with the log page showing services online/syncing.

I noticed a small thing. After clicking the Install button on the *System Check* page, it took a little while before the *Installing* page was shown (before I could see the spinner). Nothing big, but a user might think there is an issue and click on Install again or close the app not knowing it is working in the background.

**Comment by colfax23** [comment]
I was unable to reproduce the delay, but I noticed something similar in an earlier version and was able to mitigate it by a delayed call to install after the screen loads, through setTimeout.  Pushed changes - let me know if you still see the delay.

**Comment by colfax23** [comment]
Note: this also fixes #7

**Pull request merged**
