### PR TITLE
Cs/install logs

### PR DESCRIPTION
**Pull request by colfax23**
Display the logs of the install while on the Installing page.  This implements #14.

### CODE REVIEW

**Comment by remyroy** [comment]
I'm reviewing and testing this PR right now.

**Comment by colfax23** [comment]
Thanks, good suggestions @remyroy.  I'll work on those and post an update tomorrow.

**Comment by colfax23** [comment]
@remyroy ready for you to take another look.  It is a little tricky to keep the scroll at the bottom, so if the user scrolls up in the middle, it'll scroll back down when the next message arrives.  Let me know if you have a better idea for this. 
Screenshot from 2021-03-31 17-56-59

**Comment by remyroy** [comment]
This little package seems to do just that: https://www.npmjs.com/package/react-scroll-to-bottom with button that will go to bottom if the user scroll while content is added.

You solution might just be fine too. I'll have a look shortly.

**Comment by colfax23** [comment]
Great suggestion, looks like a great component.  Implemented it only to find out theres no typescript support (that I could find) so I reverted.  The current solution seems to work fine - let me know what you think.

**Comment by remyroy** [comment]
Checking right now.

**Comment by remyroy** [comment]
Everything seems good 👍

**Pull request merged**
